[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_SKIP_MIGRATIONS = "true"
  # Variables para integración con Firebase Functions
  VITE_FIREBASE_FUNCTIONS_URL = "https://us-central1-orquestapuntacana.cloudfunctions.net"
  VITE_WHATSAPP_API_URL = "https://us-central1-orquestapuntacana.cloudfunctions.net/whatsappApi"
  VITE_ENVIRONMENT = "production"

# Configuración de build específica para diferentes contextos
[context.production.environment]
  VITE_ENVIRONMENT = "production"
  VITE_DEBUG_MODE = "false"

[context.deploy-preview.environment]
  VITE_ENVIRONMENT = "preview"
  VITE_DEBUG_MODE = "true"

[context.branch-deploy.environment]
  VITE_ENVIRONMENT = "development"
  VITE_DEBUG_MODE = "true"

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

# IMPORTANT: These headers ensure the correct MIME types are sent
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/**/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200